[project]
name = "eo-bathymetry"
version = "0.1.0"
description = "scripts for deriving EO based bathymetry."
authors = ["eo-bathymetry authors"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tasks]

[dependencies]
dacite = "<=1.6.0"
geemap = "*"
geopandas = "*"
google-cloud-storage = "*"
jupyterlab = "*"
pathos = "*"
rasterio = "*"

[pypi-dependencies]
eepackages = "*"
